<a href="https://colab.research.google.com/github/megall127/LNDWEB/blob/master/ScriptPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color = black/>Operadores



Clique duas vezes no título para fazer comentários


In [ ]:
print('Hello World!')
#Posso fazer comentários usando hashtag(cerquilha).
'''
Também posso fazer comentários usando aspas simples triplas.
'''




Hello World!


' \nTambém posso fazer comentários usando aspas simples triplas.\n'

Função que interage com o usuário é chama

## Operadores Matemáticos

"+": Adição

"-": Subtração

"*": Multiplicação

"/": Divisão

"%": Módulo (resto da divisão)

"//": Divisão inteira

"**": Exponenciação (potenciação)

Para fazer raíz quadrada, devo fazer uma importação "import math".

Para calcular distâncias no plano em python:

$d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$

In [ ]:
import math
ponto_x1 = float(input("Insira a coordenada x1 para o ponto 1: "))
ponto_y1 = float(input("Insira a coordenada y1 para o ponto 1: "))
ponto_x2 = float(input("Insira a coordenada x2 para o ponto 2: "))
ponto_y2 = float(input("Insira a coordenada y2 para o ponto 2: "))
distancia = math.sqrt((ponto_x2 - ponto_x1)**2 + (ponto_y2 - ponto_y1)**2)
print("A distância entre P1 (" + str(ponto_x1) + ", " + str(ponto_y1) + ") e o ponto P2 (" + str(ponto_x2) + ", " + str(ponto_y2) + ") é: " + str(distancia) +". ")

Insira a coordenada x1 para o ponto 1: 2
Insira a coordenada y1 para o ponto 1: 6
Insira a coordenada x2 para o ponto 2: 4
Insira a coordenada y2 para o ponto 2: 9
A distância entre P1 (2.0, 6.0) e o ponto P2 (4.0, 9.0) é: 3.605551275463989. 


## Operadores de Atribuição

<font color = red> Obs: O operador "=" é usado para atribuir valores a variáveis.
O operador "==" é usado para verificar a igualdade entre dois valores.
Uma alternativa para o uso do == é o "is" ou "is not"

Claro, aqui estão os operadores de atribuição em Python:

"=": Atribuição simples


"+=": Adição e atribuição

"-=": Subtração e atribuição

"*=": Multiplicação e atribuição

"/=": Divisão e atribuição

"%=": Módulo e atribuição

"//=": Divisão inteira e atribuição

"**=": Exponenciação e atribuição



## Operadores de Comparação

"==": Igual a

"!=": Diferente de

">": Maior que

"<": Menor que

">=": Maior ou igual a

"<=": Menor ou igual a

## Operadores Lógicos

"and": Retorna True se ambas as afirmações forem verdadeiras.

and = $ \cap$

"or": Retorna True se pelo menos uma das afirmações for verdadeira.

or = $\cup$

"not": Inverte o resultado, retorna False se o resultado for verdadeiro.

not = $\neg$

In [ ]:
print( 1 < 2 and 2 > 1) #ambas verdadeiras
print(1 < 2 and 2 < 1) #apenas uma verdadeira

True
False


In [ ]:
print(1 < 2 or 1 > 2) #apenas uma verdadeira
print (2 < 1 or 1 > 2) #ambas falsas

True
False


In [ ]:
n = 1 < 2 and 2 > 1
m = 1 < 2 and 1 > 2
print(not(n))
print(not(m))

False
True


# <font color = black/>Variáveis



In [ ]:
#variável inteira#
var_tipoInteira = 5 * 3
var_tipoInteira1 = int(4 * 3)
print(var_tipoInteira, var_tipoInteira1)

#variável Flutuante
var_tipoFloat = 2.1
print(var_tipoFloat)

#variável tipo boolean

verdadeiro = True
falso = False
print(verdadeiro, falso)


15 12
2.1
True False


Tipos de variáveis:
String para tudo que for reconhecido como texto.

Int para números inteiros.

Float para valores flutuantes ($\mathbb{R} - \mathbb{Z}$). Para escrever float é necessário usar ponto.

## Declaração de variáveis

Para declarar várias variáveis, podemos compactar tudo em uma linha só.

In [ ]:
Fruta1, Fruta2, Fruta3 = [ "maçã", 'banana', 'limão']
print(Fruta1, Fruta2, Fruta3)

#podemos também atribuir, posteriomente,  valores de uma lista a variáveis
#que são declaradas depois.

ListaDeVariáveis = ['lkj', 'jhg', '123']
valor1, valor2, valor3 =  ListaDeVariáveis
print(valor1, valor2, valor3)



maçã banana limão
lkj jhg 123
variáveis


## Concatenação

In [ ]:
#concatenação

nome1 = "var"
nome2 = 'iáveis'
print(nome1 + nome2)

variáveis


## <font color =  black> Tipos de Variáveis

Tipos: String (str), Inteira (int), Flutuante (float), Booleana (bool), Complexa (complex),

In [ ]:
String = str('hello world')
Inteira = int(123)
Flutuante = float(1.4)
Booleano = bool(8)
Complexa = complex(2+1j)
Tupla = tuple(('1', 1, 'Amadeus'))
Lista = list(['banana', 123, 'amadeus'])
Dicionário = dict(nome = 'theusin', idade = '27')




## Operações entre Variáveis



In [ ]:
linhas = 7
colunas = 8
x = y = z = 13
print(linhas*colunas, x*y*z)

56 2197


## Tratamento de variáveis


Função round - Arredonda para a quantidade de casas decimais que for *desejada*

In [ ]:
arredonda = 15.12345678
round(arredonda, 3)


15.123

Função len - Esta função indica o tamanho de uma lista, de um dicionário ou a quantidade de caracteres de uma string

In [ ]:
Dicionario_2 = {'amadeus', 'orlando', 123}
tupla_1 = ('banana', 12)
apelido = 'Parafuso'


len(apelido)

8

## Tratamento de Strings

Ao receber uma string pode surgir a necessidade de fazer algumas alterações. Tais alterações podem acontecer por meio de uma função.

Funções:
Replace, startwith, endwith, count, captalizeisdigit


In [ ]:
saudacao = 'Olá mundão!'
print(saudacao)

Olá mundão!


In [ ]:
saudação = saudacao.replace('Olá mundão', 'Bom dia mundo') ###a função replace não armazena o valor. Para isso
#devemos atribuir o valor a uma nova variável.
print(saudação)

Bom dia mundo!


In [ ]:
#startswith
latim = '       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper, metus ut interdum commodo, lectus ante lacinia massa, non aliquam est mauris et elit. Fusce at quam id elit ultrices    '

latim.startswith('ultrices')

False

In [ ]:
#endswith
latim.endswith('ultrices')

True

In [ ]:
#split separa de acordo com o parâmetro que for dado. Ex: "-"
latim.split( )

['Lorem',
 'ipsum',
 'dolor',
 'sit',
 'amet,',
 'consectetur',
 'adipiscing',
 'elit.',
 'Sed',
 'ullamcorper,',
 'metus',
 'ut',
 'interdum',
 'commodo,',
 'lectus',
 'ante',
 'lacinia',
 'massa,',
 'non',
 'aliquam',
 'est',
 'mauris',
 'et',
 'elit.',
 'Fusce',
 'at',
 'quam',
 'id',
 'elit',
 'ultrices']

In [ ]:
#remove os espaços do início e do final de uma string
latim.strip()

'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper, metus ut interdum commodo, lectus ante lacinia massa, non aliquam est mauris et elit. Fusce at quam id elit ultrices'

# Condicional


## if:

A instrução if em Python é usada para testar uma condição e executar um bloco de código se a condição for verdadeira. A sintaxe da instrução if é a seguinte:
Se a condição for verdadeira, o bloco de código será executado. Se a condição for falsa, o bloco de código não será executado.

In [ ]:

# if: Condição se a pessoa for menor de idade ela poderá acessar um site.
idade = int(input("Digite sua idade: "))

if idade >= 18:
  print('Acesso válido')

## elif:

A instrução elif em Python é usada para testar uma condição adicional se a primeira condição for falsa. A sintaxe da instrução elif é a seguinte:
Se a primeira condição for verdadeira, o bloco de código 1 será executado. Se a primeira condição for falsa e a segunda condição for verdadeira, o bloco de código 2 será executado. Se ambas as condições forem falsas, nenhum bloco de código será executado.

In [ ]:

# elif: Condição se a pessoa for menor de idade ela poderá acessar um site.
idade = int(input("Digite sua idade: "))

if idade >= 18:
  print('Acesso válido')
elif idade < 18 and idade >= 14:
  print('Acesso sob análise')

## else:

A instrução else em Python é usada para executar um bloco de código se todas as outras condições forem falsas. A sintaxe da instrução else é a seguinte:
Se a primeira condição for verdadeira, o bloco de código 1 será executado. Se a primeira condição for falsa e a segunda condição for verdadeira, o bloco de código 2 será executado. Se ambas as condições forem falsas, o bloco de código 3 será executado.

In [ ]:
# else: Condição se a pessoa for menor de idade ela poderá acessar um site.
idade = int(input("Digite sua idade: "))

if idade >= 18:
  print('Acesso válido')
elif idade < 18 and idade >= 14:
  print('Acesso sob análise')
else:
  print('Acesso negado')

# <font color = black/> Lista,  Túpla e Dicionário


<font color = black>Lista - usa-se colchetes [ ].

Em uma lista, o valor pode ser alterado posteriormente. Os itens podem ser string ou valores numéricos.

<font color = black>Tupla - usa-se parênteses ( ).

Em uma tupla, o valor não pode ser alterado. Os itens podem ser string ou valores numéricos.

<font color = black>Dicionário - usa-se chaves { }.

No dicionário é necessário atribuir a cada item um determinado valor. A atribuição deve ser feita usando dois pontos (:) e posicionar uma vírgula ao final de cada linha. Tudo deve ser escrito como uma String. Os itens só podem ser strings.

Obs: os valores retornam sempre em ordem alfabética.


In [ ]:
Lista = [1, 2, 1, "matheus"]

Tupla = (1, 3, "odete")

Dicionário = {
  "Nome" : "Matheus",
  'id': 8,
  "lista" : Lista,
  "tupla" : Tupla,
}
print(Dicionário)

{'Nome': 'Matheus', 'id': 8, 'lista': [1, 2, 1, 'matheus '], 'tupla': (1, 3, 'odete')}


Uma string também pode ser vista como uma lista.

Podemos fatiar as strings da seguinte forma:



['matheus', 'Henrique']

## Lista
Criando e declarando uma lista


In [ ]:
cachorro =[] #cria uma lista vazia
numero = list(range(3, 32, 4)) #cria uma lista numérica

#função range -
# essa função é como uma  progressão aritmética
# parâmetros (primeiro elemento, último elemento, razão)
## deve ficar dentro de uma função de criação de lista

cel = list('061994439191')
#função list cria uma lista com o parâmetro sendo uma string

print(cachorro)
print(numero)
print(cel)

[]
[3, 7, 11, 15, 19, 23, 27, 31]
['0', '6', '1', '9', '9', '4', '4', '3', '9', '1', '9', '1']


### Iteráveis

Em Python, um objeto iterável é uma coleção de elementos que você pode fazer um loop (ou iterar ) através de um elemento por vez. Simplificando, um iterável é um objeto semelhante a uma lista (ou semelhante a um array).

### Acessando elementos de uma lista

É possível chamar determinados elementos de uma lista através de certos comandos.  

In [ ]:
print(cel[:5])  # deverá printar todos os elementos da lista até o quinto termo
print(cel[2:6]) # deverá imprimir do terceiro elemento até o sexto
print(cel[3:])
print(cel[-3])  # deverá imprimir o terceiro elemento da lista ordenado de trás para frente
                # nesse último caso, ao imprimir elementos negativos de uma lista
print(max(numero)) # essa função chama o maior elemento de uma lista NUMÉRICA!
print(min(numero)) # essa função chama o menor elemento de uma lista NUMÉRICA!

print(numero.index(23))


NameError: ignored

### Iterações entre Listas
Devemos ficar atentos às formas de iteração entre listas e elementos de listas.
A função sum só funciona para fazer o somatório de listas numéricas. Entretanto, se fizermos a soma de duas listas iremos obter uma concatenação.

In [ ]:
#Repetição de listas
#Ao multiplicar uma lista por um número ocorrerá a repetição da lista
#print(numero*3)

#Concatenação
#Somar listas é o mesmo que concatenar
#print(cel+numero)

#Função sort - Reverse
#Essa função retorna uma lista ordenada de trás para frente se o parâmetro for true
#Caso o parâmetro seja false a função retorna o formato natural

print(numero)
print(numero.sort(reverse = True))
len(numero) #essa função imprime a cardinalidade de uma lista






NameError: ignored

### Iteração entre elementos de uma lista

In [ ]:
from itertools import count
print(sum(numero)) #soma todos os elementos de uma lista
print(numero.count(3)) #diz quanto elementos iguais a esse existe dentro da lista
print (numero)
numero.append(6666) #adiciona o elemento(parâmetro) na última posição da lista
print(numero)
numero.remove(27)
print(numero)
numero.pop(7) #remove um elemento de acordo com sua posição (parâmetro recebe a posição)
print(numero)


109
1
[3, 7, 11, 15, 19, 23, 31]
[3, 7, 11, 15, 19, 23, 31, 6666]


ValueError: ignored

In [ ]:
listagem = [1, 5, 9, 7, 6, 41, 654]
print(listagem)
listagem.extend([1000])
print(listagem)

In [ ]:
del listagem[3] # a diferença entre a função del e a função .remove() é que del apaga o elemento de acordo com sua indexação, já o remove apaga de acordo com o valor fornecido
print(listagem)

lista_limpa = list(range(100, 1000, 50))
print(lista_limpa)
lista_limpa.clear()
print(lista_limpa)


[1, 5, 9, 1000]
[100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950]
[]


### Cópias de listas

Para fazer a cópia de uma lista é recomendável que seja usada a função .copy()

In [ ]:
sequencia = list(range(1, 100, 3))
"de_sequencia = sequencia" #se fizermos essa declaração, tudo o que for modificado na lista de_sequencia será modificado na lista sequencia
#para fazer uma cópia adequada procedemos da seguinte forma:
de_sequencia = sequencia.copy()
de_sequencia[0] = 0
print(sequencia)
print(de_sequencia)


[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]
[0, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97]


### <font color = green> Exercícios

<font color = green> Exercício 1 - Crie uma lista de 5 valores reais definidos pelo usuário. Em seguida faça o desvio médio considerando apenas dois algarismos significativos.

Obs: O desvio médio é dado pela fórmula:
$DM = \sum_{i=1}^{n}\frac{\vert x_i-\overline{x} \vert}{n-1}$

<font color = green> Exercício 2 - Faça o mesmo comando do exercício 1, porém agora trabalharemos com o desvio padrão.  

Obs: O desvio médio é dado pela fórmula:
$\sigma = \sqrt{ \frac{\sum_{i=1}^{n}( x_i-\mu )^2}{N}}$

In [ ]:
a = float(input('Digite o primeiro número: '))
b = float(input('Digite o segundo número: '))
c = float(input('Digite o segundo número: '))
d = float(input('Digite o segundo número: '))
e = float(input('Digite o segundo número: '))

lista1 = [a, b, c, d, e]

media = sum(lista1)/len(lista1)

lista2 = []

for i in lista1:

  x = round(abs(i - media), 2)
  lista2.append(x)
#DM = sum(lista2)/5

#print(DM)



Digite o primeiro número: 15
Digite o segundo número: 32.5
Digite o segundo número: 15.9774
Digite o segundo número: 65
Digite o segundo número: 82
125.62


In [ ]:
def distance_from_average(test_list):

  lista_2=[]
  media = sum(test_list)/len(test_list)

  for i in test_list:
    x = round(abs(i - media), 2)
    lista_2.append(x)
  return(lista_2)




In [ ]:
def distances_from_average(test_list):

    media = sum(test_list)/len(test_list)

    return list(round (media-i, 2) for i in test_list )


In [ ]:
from statistics import mean as md
def distances_from_average(test_list):

    media = md(test_list)

    return list(round (media-i, 2) for i in test_list )

#Estruturas de Laço

Existem duas estruturas de laço, o laço while e o laço for. Essas estruturas realizam uma determinada tarefa de acordo com um iterável.

## Laço For

Um laço for é usado para iterações sobre uma sequência (lista, tupla, dicionário, um conjunto ou uma string)



In [ ]:
for i in range(1, 50, 3):
  print(i*2)
#Note que range(1, 50, 3) é um iterável
#Sendo assim, a cada elemento i percorrido no iterável o comando é repetido

2
8
14
20
26
32
38
44
50
56
62
68
74
80
86
92
98


### Listas com estrutura de laço for

In [ ]:
#Uma forma de criar uma lista usando o laço for
a = [variavel for variavel in range(5, 51, 3)]

#Outra forma de usar é com a função nativa .append()
b = []
for valor in range(1, 10):
  b.append(valor)
print(a)
print(b)



[5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


## Laço While

O importante a se destacar para o laço while é que ele realiza determinada tarefa até que atinga uma condição verdadeira para sua parada. Caso contrário, ele se reperirá infinitamente.

In [ ]:
tabuada_do_5 = []
parametro = 10
while parametro > 0:
  tabuada_do_5.append(parametro*5)
  parametro = parametro - 1
print(tabuada_do_5)

[50, 45, 40, 35, 30, 25, 20, 15, 10, 5]


### Break  

O comando Break é usado para forçar uma parada repentinamente.


In [ ]:
#Parando o código em uma detereminada etapa do laço.
for Tabuada_5 in range(1, 11):
  if Tabuada_5 == 5:
    break
  print(Tabuada_5 * 5)

### Continue

O comando Continue é usado para que o comando seja efetuado independente de detalhes que podem aparecer dentro do laço.

Quando a instrução continue é executada, ela interrompe a execução da iteração atual do loop e continua com a próxima iteração.

In [ ]:
#Ignorando uma instrução dentro de um laço.
for Tabuada_5 in range(1, 11):
  if Tabuada_5 == 5:
     continue
     print("ignore")
  print(Tabuada_5 * 5)

# Importando pacotes

In [ ]:
import datetime

hoje = datetime.date.today()
print(hoje)
horário = datetime.datetime.today().time()
print(horário)

#criando a data de hoje
data_de_hoje = datetime.date(2024,12,13)
print(data_de_hoje)

dia = data_de_hoje.day
mes = data_de_hoje.month
ano = data_de_hoje.year

print(dia, mes, ano)

2023-12-15
13:56:51.586923
2024-12-13
13 12 2024


In [ ]:
#trabalhando com intervalos de tempo
Delta_T = data_de_hoje - hoje
print(Delta_T)

#Formato da data
dt = data_de_hoje.strftime('%d do %m de %y')
print(dt)

364 days, 0:00:00
13 do 12 de 24


In [ ]:
#somando intervalos de tempo (deltaT)
print( f'Somando 30 dias, {data_de_hoje + datetime.timedelta(days = 30)}' )
print( f'Diminuindo 30 dias, {data_de_hoje - datetime.timedelta(days = 30)}' )

Somando 30 dias, 2025-01-12
Diminuindo 30 dias, 2024-11-13


### Import Time

Pacote responsável pela criação e manipulação de data e hora.

In [ ]:
import time

greeting = input('Diga o seu nome: ')

time.sleep(5)
print('Você é um campeão, ' + greeting)

Diga o seu nome: Matheus
Você é um campeão, Matheus


In [ ]:
'Hora_atual'
Hora_ago = time.localtime()
print(Hora_ago)

'Tipo de dado.'
print(type(Hora_ago))

'Formatando hora.'
print( time.strftime('%m/%d/%Y, %H:%M:%S', Hora_ago ))

time.struct_time(tm_year=2023, tm_mon=12, tm_mday=15, tm_hour=14, tm_min=33, tm_sec=48, tm_wday=4, tm_yday=349, tm_isdst=0)
<class 'time.struct_time'>
12/15/2023, 14:33:48


### Import math

Algumas funções são mais práticas na hora de fazer cálculos matemáticos se usarmos o pacote de importação.
Ex:
abs

In [ ]:
import math
#valor absoluto ou módulo
asd = -512
print(abs(asd))

#Função Exponencial
print(math.exp(2))


#função logaritmo
#parâmetros logaritmando e base

print(math.log(64, 2))
print(math.log10(100))
print(math.log(math.exp(7), math.e))


#Funções trigonométricas
f = math.sin(math.pi/6)
print(round(math.sin(math.pi/6), 2))

#Distância entre pontos
math.dist((5, 15), (1, 2))



512
6.0
2.0
7.0
0.5
7.38905609893065


### Import Random


In [ ]:
import random

lista_aleatoria = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(random.choice(lista_aleatoria)) #Escolhe um elemento aleotório da lista

palavra = 'palavra'
print(random.choice(palavra))#Escolhe aleatoriamente uma letra da string

print(round(random.random(), 3))#Escolhe um valor aleatório entre zero e 1

inteiro_aleatorio = random.randint(0,512) #Escolhe um valor inteiro dentro desse intervalo
print(inteiro_aleatorio)

6
a
0.578
350


### Import Statistics

In [ ]:
import statistics

lista_modelo = [45, 56, 42, 78, 16, 38, 79, 42, 56, 78, 19, 45, 45]

lista_s = [0,1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584]

print(round(statistics.mean(lista_modelo), 3)) #imprime a média

statistics.median(lista_s) #imprime ordena e imprime a mediana (valor central)

print(statistics.mode(lista_modelo)) #imprime a moda (valor que mais se repete)





49.154


34

# Funções

Função é um bloco de código que é executado quando é feita uma chamada.
Uma função pode receber parâmetros ou não.

In [ ]:
#Criando uma função
def greeting():
  print('Bon Giorno')

In [ ]:
greeting()

Bon Giorno


In [ ]:
#Função com parâmetros
def produto_aleatorio(x, y):
  return x*y

In [ ]:
import random
for i in range(0, 5):
  a = random.random()
  b = random.random()
  print(produto_aleatorio(a, b))

0.04326785724005318
0.5562849775264112
0.39151362544832147
0.4116999291516745
0.11439536846987766


##Exercícios

Faça uma função que retorne o discriminante da função quadrática.

In [ ]:
def discriminante(a, b, c):
  delta = b**2 - 4*a*c
  return delta

In [ ]:
print(discriminante(1, 2, 2))

-4


##Exercícios

Faça uma função que retorne vértice da parábola

In [ ]:

def vertice_parabola(a, b, c):

  x = -b/2*a
  y = -discriminante(a, b, c)/4*a
  return x, y

In [ ]:
print('o vertice da parabola tem coordenadas: ' + str(vertice_parabola(1, 2, 3)))


o vertice da parabola tem coordenadas: (-1.0, 2.0)


##Exercícios

Faça uma função que calcule os "zeros" de uma função quadrática

In [ ]:
import math
def funcao_quadratica(a, b, c):
  if discriminante(a, b, c) < 0:
    print('não possui raíz real')
  elif discriminante(a, b, c) == 0:
    print('x = y ')
    x = -b/2*a
    print(" x = " + str(x))
  else:
    x_1 = (-b + math.sqrt(discriminante(a, b, c)))/2*a
    x_2 = (-b - math.sqrt(discriminante(a, b, c)))/2*a
    return x_1, x_2


In [ ]:
funcao_quadratica(1, 4, 4)

x = y 
 x = -2.0


## Função Lambda

A função Lambda é uma função anônima, isto é, não precisa de definição nem retorno. Usamos palavra-chave lambda, seguida de uma lista de argumentos, um operador de atribuição e um corpo de função (uma instrução).

In [ ]:
import math
funcao_simples = lambda valor: math.sqrt(valor)
##Função de maior complexidade utilizando sentenças lógicas.
Tabuada = lambda num: [ Tabu * num for Tabu in range(1, 11)]


# Tratamento de erros e estrutura TRY,EXCEPT, ELSE, FINALLY

O try serve para submeter e executar o código a ser estudado.

O except serve para classificar e tratar os erros de exceções.

O else executa o código caso não haja erros.

O finally executa um comando independente de erros ou acertos.

In [ ]:
try:
  0/0
except:
  print('Cálculo impossível!')
finally:
  print('Tente outra vez!')

Cálculo impossível!
Tente outra vez!


## Exercícios

Crie uma função que leia um número e retorne se ele é inteiro ou não.


In [ ]:
def funcaoTeste():
  a = float(input('Digite o número: '))
  print(a)



In [ ]:
try:
  funcaoTeste()
except:
  print('Esse não é um inteiro!')
while funcaoTeste() is not int:
    funcaoTeste()

else:
  print('Parabéns! Esse é um número inteiro')
#finally:
 # print('Missão concluída!')


54.4
54.3
87.8
55.0


In [ ]:
def leiaint():
  inteiro = int(input('Digite o número'))
  try:
    if type(inteiro) == int:
      print('Esse número de fato é um Inteiro.')
  except:
    print('Não é inteiro')
    inteiro = input('Digite o número')
  finally:
    print('Parabéns!')



In [ ]:
hg = input("digite seu número: ")
try:
  int(hg)
except (TypeError):
  print('Erro de escrita')
except:


digite seu número: 54.4
1.0074074074074073


# <font color = lightblue> Orientação a Objetos (Classes e Objetos)

A linguagem Python é considerada uma linguagem multiparadigma, isto é, possibilita diferentes tipos de método de programação são elas: processual, funcional, imperativa e orientação a objetos.
A orientação a obejtos ou OOP de longe é o paradigma mais recorrente em Python, pois possibilita a interação entre objetos de forma mais eficaz. A OOP é sustentada em quatro pilares:

I - Abstração:Na programação orientada a objetos, a construção dos objetos é baseada em uma Classeque representa as características desse objeto.


II - Encapsulamento: O princípio de encapsulamento consiste em "esconder" a parte funcional dos objetos de forma que quem utiliza não tenha que conhecer mais do que o necessário para utilizá-lo.


III - A herança: Consiste em determinar que uma classe existe por si mesma, porém, ela é uma outra classe em sua essência.

IV - Polimorfismo: O conceito do polimorfismo é permitir que comportamentos comuns a $n$ tipos de classes possam ser definidos de forma específica para cada classe.

In [ ]:
  class Pessoa:
  # Método construtor
    def __init__ (self, Nome, Idade):
      self.nome = Nome
      self.idade = int(Idade)

    def Ano_Bissexto(self):
      print('Oi', self.nome, 'Você nasceu em um ano bissexto! Parabéns!')
    def Ano_nbissexto(self):
      print('Oi', self.nome, 'Você nasceu em um ano comum.')

  # Função

    def Calculo_Idade(self):
      if self.idade % 4 == 0:
        print('Se você tem ', self.idade)
        return self.Ano_Bissexto()
      else:
        return self.Ano_nbissexto()

In [ ]:
vari_1 = Pessoa("Matheus", 1996)
print(vari_1.Calculo_Idade())

Se você tem  1996
Oi Matheus Você nasceu em um ano bissexto! Parabéns!
None


# <font color = orange> Arrays e nd-arrays

Arrays simples e multidimencionais são extremamente úteis quando estamos lidando com um único tipo de dado, especialmente se forem do tipo int ou float. A diferença entre arrays simples e N-dimensional arrays (arrays multidimensionais) em Python está principalmente na estrutura e na forma como os dados são organizados e acessados. Vamos explorar isso com mais detalhes adiante neste tópico.

10.1.Arrays
Em Python, a estrutura de dados mais próxima do conceito de "array" em outras linguagens de programação são as listas. No entanto, Python também possui arrays, mas eles são menos comuns e têm algumas diferenças em comparação com listas.

Listas: As listas em Python como já visto antes são coleções ordenadas e mutáveis de elementos. Elas podem armazenar diferentes tipos de dados (números, strings, objetos, etc.).

Arrays: Arrays em Python são oferecidos pelo módulo array, que fornece uma estrutura de dados mais eficiente em termos de memória para armazenar grandes coleções de dados homogêneos (todos do mesmo tipo).

Devemos importar a bibliotéca array (import > array) ou numpy (import > numpy) para criar os arrays.
import array


In [ ]:
#Criando um array de inteiros
import array
import numpy as np

meu_array = np.array([1, 2, 3, 4, 5])
print(meu_array)
#Acessando Arrays
#Podemos acessar elementos individuais de um array usando índices. Os índices começam em  0 .
#Acessando o primeiro elemento
print(meu_array[0])

#Acessando o terceiro elemento
print(meu_array[2])

#Acessando o último elemento
print(meu_array[-1])

[1 2 3 4 5]
1
3
5


# <font color = yellow> Códigos de Tipo em Arrays
Códigos de tipo são caracteres que especificam o tipo de elementos que um array do módulo array em Python pode armazenar. Eles garantem que todos os elementos do array sejam do mesmo tipo, o que é importante para a eficiência de memória e desempenho. Podemos listar três diretrizes.

I - Eficiência de Memória: Arrays utilizam uma quantidade fixa de memória por elemento, baseada no tipo de dado. Isso é mais eficiente do que listas, que podem armazenar elementos de diferentes tipos e têm mais overhead.

II - Desempenho: Operações em arrays são geralmente mais rápidas que em listas, pois o tipo de dado é conhecido e fixo.

III - Interoperabilidade: Facilita a integração com outras linguagens (como  𝐶 ) que esperam dados em formatos específicos.
Código de tipo

Escolher o código de tipo depende do tipo de dados que você precisa armazenar no array. São eles:

Inteiros Pequenos: Use 'b' para inteiros com sinal de  1  byte, ou 'B' para inteiros sem sinal de  1  byte.

Inteiros Médios: Use 'h' ou 'H' para inteiros de  2  bytes.

Inteiros Grandes: Use 'i', 'I', 'l', 'L', 'q', ou 'Q' dependendo do tamanho e se são com ou sem sinal.

Números de Ponto Flutuante: Use 'f' para floats (precisão simples) e 'd' para doubles (precisão dupla).

In [ ]:
#Criando um array de inteiros com o código de tipo 'i'
import array

meu_array = array.array('i', [1, 2, 3, 4, 5])

#Acessando elementos
print(meu_array[0])

#Criando um array de flutuantes com o código de tipo 'd'
meu_array = array.array('d', [1.1, 2.2, 3.3, 4.4, 5.5])

#Acessando elementos
print(meu_array[0])

1
1.1


<font color = lightblue>N-dimensional Arrays

ndarray (abreviação de N-dimensional array) é o principal objeto da biblioteca numpy. Ele representa um array multidimensional de elementos de um único tipo de dados. É altamente eficiente para operações matemáticas e científicas devido à sua implementação otimizada e à capacidade de operar sobre grandes volumes de dados de forma rápida e eficaz. Podemos listar três carcaterísticas importantes.

I - Multidimensionalidade: Pode ser um array de qualquer dimensão, desde 1D (vetor) até nD (tensores).

II - Homogeneidade: Todos os elementos do ndarray são do mesmo tipo de dados.

III - Operações Vetorizadas: Suporta operações aritméticas e funções matemáticas aplicadas a todos os elementos de forma vetorizada, o que melhora significativamente o desempenho.

## <font color = yellow> Criação de ndarrays
Podemos criar um ndarray a partir de listas ou outras estruturas de dados usando a função np.array().
import numpy as np

In [ ]:
#Criando um array 1D
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
#print(array_1d)

#Criando um array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
#print(array_2d)

#Criando um array 3D
array_3d = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(array_3d)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


### Outras formas de criar arrays

Criando arrays com zeros.

In [ ]:
#1D
azeros = np.zeros(5)
azeros

In [ ]:
#2D
bzeros = np.zeros((3, 4)) #3 linhas e 4 colunas
bzeros

In [ ]:
#3D
czeros = np.zeros((3, 4, 2))# 3 páginas, 4 linhas e 2 colunas
czeros

### Criando arrays com uns.

In [ ]:
#1D
aones = np.ones(5)
aones

In [ ]:
#2D
bones = np.ones((3,4))
bones

In [ ]:
#3D
cones = np.ones((3,4,2))
cones

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

### Criando ND-arrays Com valores aleatórios

In [ ]:
#criando um nd-array de 3 dimensões randomizado com 3 páginas, 4 linhas e 3 colunas
asd = np.random.randint(0, 101, (3,4,3))
asd


array([[[86, 33, 86],
        [14, 29, 15],
        [21, 75, 49],
        [91, 59, 64]],

       [[40, 24, 72],
        [22, 39,  8],
        [25, 24, 58],
        [80, 97, 10]],

       [[33, 46, 25],
        [ 7, 30, 99],
        [ 7, 91,  2],
        [43, 56, 58]]])

### Acessando nd-arrays

In [ ]:
#Resganando um elemento da segunda página, terceira linha, primeira coluna.
asd[1][2][0]

25

In [ ]:
#Acessando da segunda página da segunda linha em diante
asd[1][1:]

array([[22, 39,  8],
       [25, 24, 58],
       [80, 97, 10]])

In [ ]:
#Acessando todos os elementos da terceira coluna em todas as linhas da terceira página
#Lista enumerada de linhas.
linhas_asd = [0,1,2,3]
colunas_asd = [2,2,2,2]
asd [2][linhas_asd, colunas_asd]

array([25, 99,  2, 58])

In [ ]:
asd[2][:, 2]

array([25, 99,  2, 58])

In [ ]:
asd[2][:][2]


array([ 7, 91,  2])

### (Fatiamento/slicing)

In [ ]:
qwe = np.random.randint(0, 101, (2,8,10))


In [ ]:
qwe

array([[[  4,  28,  56,  38,  66,  78,  30,  88,  81,  10],
        [ 62,  31,  45,  77,  67,  97,  50,  92,  95,  50],
        [  6,  89,  41,  66,   3,  93,  90,  60,  47,   8],
        [ 61,  59,   0,  76,  26,  84,  67,  71,   7,  24],
        [ 76,  34,  86,  17,  22,  40,  24,  93,  88,  77],
        [ 84,  17,  50,  64,  89,  82,   6,  69,  92,  78],
        [ 33,  90,  99,  64,  55,  47,   7,  82,  49,  96],
        [ 35,  79,  12,  17,  63,  82,  79,   4,  79,  42]],

       [[ 40,  60,  95,  26,  12,  61,  33,  57,  41,   0],
        [ 59,  82,  75,  47,  75,  19,   9,  95,  55,  64],
        [ 81,  94,  74,  70,  72,  38,  74,  70,  74,  28],
        [ 83,  97,  51,  62,  78,  70,  86,  32,  40,  78],
        [ 87,  71,  92,   6,  61,  77,  85, 100,  28,  30],
        [ 61,  67,  67,  13,  73, 100,  67,  49,  40,  58],
        [ 36,  31,  28,  37,  88,  23,  52,  94,  55,  19],
        [ 11,  20, 100,  45,  94,  51,  81,   9,  21,  78]]])

In [ ]:
qwe[1][2:8,::2]


array([[ 81,  74,  72,  74,  74],
       [ 83,  51,  78,  86,  40],
       [ 87,  92,  61,  85,  28],
       [ 61,  67,  73,  67,  40],
       [ 36,  28,  88,  52,  55],
       [ 11, 100,  94,  81,  21]])

### Consultas em um array

In [ ]:
qwe>10

In [ ]:
qwe[qwe>20]

array([ 28,  56,  38,  66,  78,  30,  88,  81,  62,  31,  45,  77,  67,
        97,  50,  92,  95,  50,  89,  41,  66,  93,  90,  60,  47,  61,
        59,  76,  26,  84,  67,  71,  24,  76,  34,  86,  22,  40,  24,
        93,  88,  77,  84,  50,  64,  89,  82,  69,  92,  78,  33,  90,
        99,  64,  55,  47,  82,  49,  96,  35,  79,  63,  82,  79,  79,
        42,  40,  60,  95,  26,  61,  33,  57,  41,  59,  82,  75,  47,
        75,  95,  55,  64,  81,  94,  74,  70,  72,  38,  74,  70,  74,
        28,  83,  97,  51,  62,  78,  70,  86,  32,  40,  78,  87,  71,
        92,  61,  77,  85, 100,  28,  30,  61,  67,  67,  73, 100,  67,
        49,  40,  58,  36,  31,  28,  37,  88,  23,  52,  94,  55, 100,
        45,  94,  51,  81,  21,  78])

In [1]:
import numpy as np
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


In [5]:
a = np.zeros(10) + 4
a

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [4]:
b = np.full(10, 4)
b

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])